name: Database Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Run schema changes on Azure MySQL
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_ADMIN_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql \
            --host="$DB_HOST" \
            --user="$DB_USER" \
            --password="$DB_PASSWORD" \
            --ssl-mode=REQUIRED \
            "$DB_NAME" < schema_changes_git.sql
